version: "3.9"
services:
  backend:
    build:
      context: back
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    env_file:
      - ./back/.env
    volumes:
      - ./back/data:/app/data
      - ./back/embeddings:/app/embeddings
      - ./back/results:/app/results
  frontend:
    build:
      context: front-next
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend